[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"


[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8087"]
  token = "admin123"
  bucket = "weather"
  organization = "weather_org"

[[inputs.prometheus]]
  urls = ["http://weather-bot:5000/metrics"]
  name_prefix = "weather_"
  metric_version = 2